---
apiVersion: v1
kind: Secret
metadata:
  name: heketi-secret
data:
  # echo -n "admin_key" | base64
  key: YWRtaW5fa2V5
type: kubernetes.io/glusterfs

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "my-gfs-storageclass"
  annotations:
    # 設定為預設的 storage class
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.99.1.199:8080"
  clusterid: "a46d8cd541d9e12fea77fec876ffb5e9"
  restauthenabled: "true"
  restuser: "admin"
  secretNamespace: "default"
  secretName: "heketi-secret"
  gidMin: "40000"
  gidMax: "50000"
  volumetype: "replicate:2"
allowVolumeExpansion: true
reclaimPolicy: Retain
